import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowUp, Sparkles } from "lucide-react";
import { PageHeader } from "@/components/devpulse/AppShell";
import { QueryState } from "@/components/ui-kit/QueryState";
import { Skeleton } from "@/components/ui-kit/Skeleton";
import { Spinner } from "@/components/ui-kit/Spinner";
import { EmptyState } from "@/components/ui-kit/EmptyState";
import { ErrorState } from "@/components/ui-kit/ErrorState";
import { queryKeys } from "@/lib/api/queryKeys";
import { aiService } from "@/lib/api/services";
import { useAuth } from "@/hooks/useAuth";
import { formatDate, initialsFrom, timeAgo } from "@/lib/format";

export const Route = createFileRoute("/app/ai")({
  head: () => ({
    meta: [
      { title: "AI Workspace — DevPulse" },
      {
        name: "description",
        content:
          "Chat with your engineering copilot: weekly summaries, repository insights, and recommendations.",
      },
      { property: "og:title", content: "AI Workspace — DevPulse" },
      {
        property: "og:description",
        content: "Your engineering copilot, grounded in your GitHub activity.",
      },
    ],
  }),
  component: AIWorkspace,
});

/** Static UI copy — prompt starters, not application data. */
const SUGGESTIONS = [
  "Summarize this week's engineering activity",
  "Which PRs are stuck in review?",
  "What are the top risks across my repositories?",
  "Who reviewed the most PRs last week?",
];

function AIWorkspace() {
  const { user } = useAuth();
  const qc = useQueryClient();
  const [conversationId, setConversationId] = useState<string | null>(null);
  const [input, setInput] = useState("");

  const conversationsQ = useQuery({
    queryKey: queryKeys.ai.conversations,
    queryFn: () => aiService.conversations(),
  });

  const threadQ = useQuery({
    queryKey: queryKeys.ai.conversation(conversationId ?? ""),
    queryFn: () => aiService.conversation(conversationId as string),
    enabled: !!conversationId,
  });

  const weeklyQ = useQuery({
    queryKey: queryKeys.ai.weeklySummary,
    queryFn: () => aiService.weeklySummary(),
  });

  const recommendationsQ = useQuery({
    queryKey: queryKeys.ai.recommendations,
    queryFn: () => aiService.recommendations(),
  });

  const send = useMutation({
    mutationFn: (content: string) => aiService.sendMessage(conversationId, content),
    onSuccess: (res) => {
      setConversationId(res.conversationId);
      qc.invalidateQueries({ queryKey: queryKeys.ai.conversations });
      qc.invalidateQueries({
        queryKey: queryKeys.ai.conversation(res.conversationId),
      });
    },
  });

  function submit(content: string) {
    const value = content.trim();
    if (!value || send.isPending) return;
    setInput("");
    send.mutate(value);
  }

  const messages = threadQ.data?.messages ?? [];

  return (
    <>
      <PageHeader
        title="AI Workspace"
        subtitle="Your engineering copilot — grounded in your GitHub activity."
      />

      <div className="grid gap-4 lg:grid-cols-[1fr_280px]">
        <div className="flex min-h-[560px] flex-col rounded-xl border border-border bg-surface">
          <div className="flex-1 space-y-4 overflow-y-auto p-6">
            {!conversationId ? (
              <EmptyState
                icon={Sparkles}
                title="Ask your first question"
                description="Responses are generated by the DevPulse backend from your synchronized GitHub activity."
                className="border-0 bg-transparent"
              />
            ) : threadQ.isPending ? (
              <div className="space-y-3">
                <Skeleton className="h-16 w-2/3" />
                <Skeleton className="ml-auto h-10 w-1/2" />
                <Skeleton className="h-20 w-3/4" />
              </div>
            ) : threadQ.isError ? (
              <ErrorState
                error={threadQ.error}
                title="Couldn't load this conversation"
                onRetry={() => threadQ.refetch()}
              />
            ) : (
              messages.map((m) => (
                <Message
                  key={m.id}
                  role={m.role}
                  content={m.content}
                  initials={initialsFrom(user?.name || user?.username)}
                />
              ))
            )}
            {send.isPending ? (
              <div className="flex items-center gap-2 text-xs text-muted-foreground">
                <Spinner /> Generating response…
              </div>
            ) : null}
            {send.isError ? (
              <ErrorState
                error={send.error}
                title="The assistant couldn't respond"
                onRetry={() => send.reset()}
              />
            ) : null}
          </div>

          <div className="border-t border-border p-4">
            <div className="flex flex-wrap gap-2 pb-3">
              {SUGGESTIONS.map((s) => (
                <button
                  key={s}
                  onClick={() => submit(s)}
                  disabled={send.isPending}
                  className="rounded-full border border-border bg-background px-3 py-1 text-xs text-muted-foreground transition-colors hover:text-foreground disabled:opacity-50"
                >
                  {s}
                </button>
              ))}
            </div>
            <form
              onSubmit={(e) => {
                e.preventDefault();
                submit(input);
              }}
              className="flex items-center gap-2 rounded-lg border border-border bg-background p-2 focus-within:border-primary"
            >
              <Sparkles className="ml-1 h-4 w-4 text-primary" />
              <input
                value={input}
                onChange={(e) => setInput(e.target.value)}
                placeholder="Ask about repos, PRs, workflows…"
                className="flex-1 bg-transparent text-sm placeholder:text-muted-foreground focus:outline-none"
              />
              <button
                type="submit"
                disabled={send.isPending || !input.trim()}
                className="grid h-7 w-7 place-items-center rounded-md bg-primary text-primary-foreground disabled:opacity-50"
                aria-label="Send message"
              >
                <ArrowUp className="h-3.5 w-3.5" />
              </button>
            </form>
          </div>
        </div>

        <aside className="space-y-4">
          <Card title="Recent conversations">
            <QueryState
              query={conversationsQ}
              skeleton={
                <div className="space-y-2">
                  {Array.from({ length: 4 }).map((_, i) => (
                    <Skeleton key={i} className="h-7 w-full" />
                  ))}
                </div>
              }
              emptyTitle="No conversations yet"
              emptyDescription="Your AI threads will be listed here."
            >
              {(items) => (
                <ul className="space-y-2 text-sm">
                  {items.map((c) => (
                    <li key={c.id}>
                      <button
                        onClick={() => setConversationId(c.id)}
                        className={`w-full truncate rounded-md px-2 py-1.5 text-left transition-colors hover:bg-accent hover:text-foreground ${
                          conversationId === c.id
                            ? "bg-accent text-foreground"
                            : "text-muted-foreground"
                        }`}
                      >
                        {c.title} · {timeAgo(c.updatedAt)}
                      </button>
                    </li>
                  ))}
                </ul>
              )}
            </QueryState>
          </Card>

          <Card title="Weekly summary">
            <QueryState
              query={weeklyQ}
              skeleton={<Skeleton className="h-24 w-full" />}
              emptyTitle="No summary yet"
              emptyDescription="A weekly summary is generated once enough activity is synced."
            >
              {(w) => (
                <div className="space-y-2 text-sm">
                  <p className="text-foreground/90">{w.summary}</p>
                  <ul className="list-disc space-y-1 pl-5 text-xs text-muted-foreground">
                    {w.highlights.map((h) => (
                      <li key={h}>{h}</li>
                    ))}
                  </ul>
                  <p className="text-[10px] uppercase tracking-widest text-muted-foreground">
                    {formatDate(w.generatedAt)}
                  </p>
                </div>
              )}
            </QueryState>
          </Card>

          <Card title="Recommendations">
            <QueryState
              query={recommendationsQ}
              skeleton={
                <div className="space-y-2">
                  <Skeleton className="h-12 w-full" />
                  <Skeleton className="h-12 w-full" />
                </div>
              }
              emptyTitle="No recommendations"
              emptyDescription="Recommendations appear after your repositories are analyzed."
            >
              {(recs) => (
                <ul className="space-y-3 text-sm">
                  {recs.map((r) => (
                    <li key={r.id}>
                      <div
                        className={`text-[11px] font-semibold uppercase tracking-widest ${
                          r.severity === "critical"
                            ? "text-destructive"
                            : r.severity === "warning"
                              ? "text-warning"
                              : "text-primary"
                        }`}
                      >
                        {r.title}
                      </div>
                      <p className="mt-0.5 text-xs text-muted-foreground">{r.summary}</p>
                    </li>
                  ))}
                </ul>
              )}
            </QueryState>
          </Card>
        </aside>
      </div>
    </>
  );
}

function Message({
  role,
  content,
  initials,
}: {
  role: "user" | "assistant";
  content: string;
  initials: string;
}) {
  const isUser = role === "user";
  return (
    <div className={`flex gap-3 ${isUser ? "flex-row-reverse" : ""}`}>
      <div
        className={`grid h-7 w-7 shrink-0 place-items-center rounded-md text-xs font-medium ${
          isUser ? "bg-primary/15 text-primary" : "bg-foreground text-background"
        }`}
      >
        {isUser ? initials : <Sparkles className="h-3.5 w-3.5" />}
      </div>
      <div
        className={`max-w-[80%] whitespace-pre-wrap rounded-lg px-4 py-2.5 text-sm leading-relaxed ${
          isUser
            ? "bg-primary/10 text-foreground"
            : "border border-border bg-background text-foreground"
        }`}
      >
        {content}
      </div>
    </div>
  );
}

function Card({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-xl border border-border bg-surface p-4">
      <div className="mb-3 text-[11px] font-semibold uppercase tracking-widest text-muted-foreground">
        {title}
      </div>
      {children}
    </div>
  );
}
