/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as HomepageRouteImport } from './routes/homepage'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAiRouteImport } from './routes/app.ai'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppRepositoriesRouteImport } from './routes/app.repositories'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRepositoriesIndexRouteImport } from './routes/app.repositories.index'
import { Route as AppRepositoriesIdRouteImport } from './routes/app.repositories.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const HomepageRoute = HomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoriesRoute = AppRepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoriesIndexRoute = AppRepositoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRepositoriesRoute,
} as any)
const AppRepositoriesIdRoute = AppRepositoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRepositoriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/homepage': typeof HomepageRoute
  '/login': typeof LoginRoute
  '/app/ai': typeof AppAiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/repositories': typeof AppRepositoriesRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/repositories/$id': typeof AppRepositoriesIdRoute
  '/app/repositories/': typeof AppRepositoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/homepage': typeof HomepageRoute
  '/login': typeof LoginRoute
  '/app/ai': typeof AppAiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/repositories/$id': typeof AppRepositoriesIdRoute
  '/app/repositories': typeof AppRepositoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/homepage': typeof HomepageRoute
  '/login': typeof LoginRoute
  '/app/ai': typeof AppAiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/repositories': typeof AppRepositoriesRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/repositories/$id': typeof AppRepositoriesIdRoute
  '/app/repositories/': typeof AppRepositoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/homepage'
    | '/login'
    | '/app/ai'
    | '/app/analytics'
    | '/app/dashboard'
    | '/app/notifications'
    | '/app/profile'
    | '/app/reports'
    | '/app/repositories'
    | '/app/settings'
    | '/app/'
    | '/app/repositories/$id'
    | '/app/repositories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/homepage'
    | '/login'
    | '/app/ai'
    | '/app/analytics'
    | '/app/dashboard'
    | '/app/notifications'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app'
    | '/app/repositories/$id'
    | '/app/repositories'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/homepage'
    | '/login'
    | '/app/ai'
    | '/app/analytics'
    | '/app/dashboard'
    | '/app/notifications'
    | '/app/profile'
    | '/app/reports'
    | '/app/repositories'
    | '/app/settings'
    | '/app/'
    | '/app/repositories/$id'
    | '/app/repositories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  HomepageRoute: typeof HomepageRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homepage': {
      id: '/homepage'
      path: '/homepage'
      fullPath: '/homepage'
      preLoaderRoute: typeof HomepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/repositories': {
      id: '/app/repositories'
      path: '/repositories'
      fullPath: '/app/repositories'
      preLoaderRoute: typeof AppRepositoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/repositories/': {
      id: '/app/repositories/'
      path: '/'
      fullPath: '/app/repositories/'
      preLoaderRoute: typeof AppRepositoriesIndexRouteImport
      parentRoute: typeof AppRepositoriesRoute
    }
    '/app/repositories/$id': {
      id: '/app/repositories/$id'
      path: '/$id'
      fullPath: '/app/repositories/$id'
      preLoaderRoute: typeof AppRepositoriesIdRouteImport
      parentRoute: typeof AppRepositoriesRoute
    }
  }
}

interface AppRepositoriesRouteChildren {
  AppRepositoriesIdRoute: typeof AppRepositoriesIdRoute
  AppRepositoriesIndexRoute: typeof AppRepositoriesIndexRoute
}

const AppRepositoriesRouteChildren: AppRepositoriesRouteChildren = {
  AppRepositoriesIdRoute: AppRepositoriesIdRoute,
  AppRepositoriesIndexRoute: AppRepositoriesIndexRoute,
}

const AppRepositoriesRouteWithChildren = AppRepositoriesRoute._addFileChildren(
  AppRepositoriesRouteChildren,
)

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRepositoriesRoute: typeof AppRepositoriesRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppRepositoriesRoute: AppRepositoriesRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  HomepageRoute: HomepageRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
